# Generated by Django 3.2.7 on 2022-01-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Полное описание')),
                ('image', models.ImageField(blank=True, default='dogs/img/default.jpg', null=True, upload_to='dogs/img/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
                'ordering': ['name'],
            },
        ),
    ]
