# Generated by Django 3.2.7 on 2021-10-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, default='dog/img/default.jpg', null=True, upload_to='dogs/img/'),
        ),
    ]
