# Generated by Django 3.2.7 on 2021-10-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_alter_dog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, default='dogs/img/default.jpg', null=True, upload_to='dogs/img/'),
        ),
    ]
