# Generated by Django 3.2.7 on 2022-02-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Полное описание')),
                ('years', models.PositiveIntegerField(verbose_name='Продолжительность жизни')),
                ('picture_name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cats/img/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Кошка',
                'verbose_name_plural': 'Кошки',
                'ordering': ['name'],
            },
        ),
    ]
