# Generated by Django 3.2.7 on 2021-10-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_cat_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='author',
        ),
    ]
