# Generated by Django 3.2.7 on 2021-10-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_alter_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cats/img/'),
        ),
    ]
