# Generated by Django 3.2.7 on 2021-10-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_alter_cat_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['name'], 'verbose_name': 'Кошка', 'verbose_name_plural': 'Кошки'},
        ),
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cats/img/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='text',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='years',
            field=models.PositiveIntegerField(verbose_name='Продолжительность жизни'),
        ),
    ]
